### ISSUE TITLE
riak 0.9.5 explodes in beefcake

### ISSUE THREAD

**Issue by be9** [riak-ripple/ripple#179]
I have riak-search 0.14.2 and riak 0.9.5 here.

After upgrade to 0.9.5 (it was some post-0.9.3 git before) I get the following:

```
/home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/beefcake-0.3.4/lib/beefcake.rb:212:in `block in ==': undefined method `[]' for false:FalseClass (NoMethodError)
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/beefcake-0.3.4/lib/beefcake.rb:212:in `each'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/beefcake-0.3.4/lib/beefcake.rb:212:in `all?'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/beefcake-0.3.4/lib/beefcake.rb:212:in `=='
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/beefcake-0.3.4/lib/beefcake.rb:175:in `block in decode'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/beefcake-0.3.4/lib/beefcake.rb:174:in `each'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/beefcake-0.3.4/lib/beefcake.rb:174:in `decode'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/riak-client-0.9.5/lib/riak/client/beefcake_protobuffs_backend.rb:177:in `decode_response'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/riak-client-0.9.5/lib/riak/client/beefcake_protobuffs_backend.rb:87:in `get_bucket_props'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/riak-client-0.9.5/lib/riak/bucket.rb:91:in `props'
    from /home/od/work/stylesclub/config/initializers/riak_search.rb:4:in `<top (required)>'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:235:in `load'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:235:in `block in load'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:227:in `load_dependency'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:235:in `load'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/railties-3.0.9/lib/rails/engine.rb:201:in `block (2 levels) in <class:Engine>'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/railties-3.0.9/lib/rails/engine.rb:200:in `each'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/railties-3.0.9/lib/rails/engine.rb:200:in `block in <class:Engine>'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/railties-3.0.9/lib/rails/initializable.rb:25:in `instance_exec'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/railties-3.0.9/lib/rails/initializable.rb:25:in `run'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/railties-3.0.9/lib/rails/initializable.rb:50:in `block in run_initializers'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/railties-3.0.9/lib/rails/initializable.rb:49:in `each'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/railties-3.0.9/lib/rails/initializable.rb:49:in `run_initializers'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/railties-3.0.9/lib/rails/application.rb:134:in `initialize!'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/railties-3.0.9/lib/rails/application.rb:77:in `method_missing'
    from /home/od/work/stylesclub/config/environment.rb:5:in `<top (required)>'
    from /home/od/work/stylesclub/spec/spec_helper.rb:3:in `require'
    from /home/od/work/stylesclub/spec/spec_helper.rb:3:in `<top (required)>'
    from /home/od/work/stylesclub/spec/lib/ext/ripple_spec.rb:1:in `require'
    from /home/od/work/stylesclub/spec/lib/ext/ripple_spec.rb:1:in `<top (required)>'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/rspec-core-2.6.4/lib/rspec/core/configuration.rb:419:in `load'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/rspec-core-2.6.4/lib/rspec/core/configuration.rb:419:in `block in load_spec_files'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/rspec-core-2.6.4/lib/rspec/core/configuration.rb:419:in `map'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/rspec-core-2.6.4/lib/rspec/core/configuration.rb:419:in `load_spec_files'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/rspec-core-2.6.4/lib/rspec/core/command_line.rb:18:in `run'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/rspec-core-2.6.4/lib/rspec/core/runner.rb:80:in `run_in_process'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/rspec-core-2.6.4/lib/rspec/core/runner.rb:69:in `run'
    from /home/od/.rvm/gems/ruby-1.9.2-p180@stylesclub/gems/rspec-core-2.6.4/lib/rspec/core/runner.rb:11:in `block in autorun'
rake aborted!
```

Here's config/initializers/riak_search.rb:

``` ruby
require 'riak/search'

bucket = User.bucket
#bucket.props['precommit'] = []
bucket.enable_index!
```

Commenting out the last line (`bucket.enable_index!`) resolves the situation, but disables the index.
